# Generated by Django 2.2.6 on 2019-10-21 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_add_view_future_post_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date', 'title'], 'permissions': (('view_future_post', 'Can view unpublished Post'), ('add_tasking', 'Can add task')), 'verbose_name': 'blog post'},
        ),
    ]
