# Generated by Django 2.2.6 on 2019-10-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_remove_tasking_tags'),
        ('Blog', '0003_auto_20191020_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tasking',
            field=models.ManyToManyField(related_name='tasking', to='organizer.Tasking'),
        ),
    ]
