# Generated by Django 2.2.6 on 2019-10-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_add_add_tasking_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasking',
            name='assigned_date',
            field=models.DateTimeField(auto_now_add=True, unique=True, verbose_name='date assigned'),
        ),
        migrations.AlterField(
            model_name='tasking',
            name='name',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='tasking',
            name='slug',
            field=models.SlugField(max_length=32, unique=True),
        ),
    ]
