# Generated by Django 2.2.6 on 2019-10-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_remove_tasking_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasking',
            name='project_codename',
            field=models.CharField(db_index=True, default='SandStorm', max_length=32),
        ),
    ]
